source 'git@github.com:salemove/ios-cocoapods-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, :deployment_target => '10.0'

def sdk
    pod 'SalemoveSDK', '0.7.9'
end

target 'SaleMove' do
  sdk
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.3'
        end
    end
end
